### ISSUE TITLE
Quantification library license

### ISSUE THREAD

**Issue by pawel-czyz** [Arctickirillas/Rubrication#1]
Dear Dr Karpov and Dr Rudakov,

Recently I have come across your article NRU-HSE at SemEval-2016 Task 4: Comparative Analysis of Two Iterative Methods Using Quantification Library (doi:10.18653/v1/S16-1025) which investigates different methods of quantification, and a repository accompanying it (https://github.com/Arctickirillas/Rubrication). I must admit that I am impressed by the quality of your article and the amount of work you have put into the library. I would like to use it to compare standard quantification algorithms with a new one (https://arxiv.org/abs/1908.09157). I wonder if your repository is distributed under any license that would allow me to use it for this purpose (e.g. MIT, GPL, or Apache).

Yours sincerely,
Paweł Czyż

**Comment by Arctickirillas** [comment]
Hello!
You can use our repository. I will add MIT licence the other day.
Sincerely,Rudakov Kirill.

  01.07.2020, 13:15, Paweł Czyż <notifications@github.com>


  Dear Dr Karpov and Dr Rudakov,

  Recently I have come across your article NRU-HSE at SemEval-2016 Task 4:
  Comparative Analysis of Two Iterative Methods Using Quantification Library
  (doi:10.18653/v1/S16-1025) which investigates different methods of
  quantification, and a repository accompanying it (https://github.com/Arctickirillas/Rubrication).
  I must admit that I am impressed by the quality of your article and the
  amount of work you have put into the library. I would like to use it to
  compare standard quantification algorithms with a new one (https://arxiv.org/abs/1908.09157).
  I wonder if your repository is distributed under any license that would allow
  me to use it for this purpose (e.g. MIT, GPL, or Apache).

  Yours sincerely,
  Paweł Czyż

**Comment by pawel-czyz** [comment]
Thank you very much!
